### PR TITLE
Add API that returns threads with flagged posts

### PR DESCRIPTION
**Pull request by kluo**
@azimpradhan Thanks.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@azimpradhan We only need to worry about the latest commit: https://github.com/Stanford-Online/cs_comments_service/commit/a059166d5809bffb81b96134d261c85ce44c9eaf

**Comment by stvstnfrd** [comment]
@kluo You based this off of a an already existing endpoint, right? Assuming so, which one and where can I find it?

**Comment by kluo** [comment]
@stvstnfrd here: https://github.com/Stanford-Online/cs_comments_service/blob/master/lib/tasks/flags.rake

**Comment by azimpradhan** [comment]
@kluo , I made a comment regarding adding a scope for getting flagged content. Other than that +1 from me

**Comment by kluo** [comment]
Thanks for the tip @azimpradhan

**Comment by stvstnfrd** [comment]
One question, otherwise, I defer to you and Azim.

+1 on my end.

**Comment by stvstnfrd** [comment]
This looks good to me. That said, I'd still like to take another look once your squash your commits; it's a bit difficult to parse your 3 changes out of the rest of this merge.

I have enabled Travis-CI/coveralls.io integration for this repo.
It should kick in when you push next.

**Comment by stvstnfrd** [comment]
After we merge/release this, we should PR it upstream.

**Comment by stvstnfrd** [comment]
+1

**Comment by stvstnfrd** [comment]
and with the +1 from @azimpradhan , I think you can merge when ready.

**Comment by azimpradhan** [comment]
Looks good to me :+1:

**Pull request merged**
